### ISSUE TITLE
Update ENA URL.

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/plant-brapi-etl-faidare#32]
ENA URL is pointing to your old data browser (https://www.ebi.ac.uk/ena/data/view/PRJNA498400) instead of the new one (https://www.ebi.ac.uk/ena/browser/view/PRJNA498400).
This should be updated in ENA endpoint. This issue is just  reminder.

**Comment by brunocontrerasmoreira** [comment]
Hi @cpommier , I updated the URL at https://github.com/EnsemblGenomes/ebi_plant_index and I am running it now. It takes < 1 day.
I was running it roughly once per Ensembl release and since it works I could cron it. How often do yoy think this needs to be updated? Once per month?

**Comment by cpommier** [comment]
Thanks @brunocontrerasmoreira there seems to be a typo in the URL though (browse should be browser). I have left a comment. 

I think running it monthly as you proposed should be okay.

**Comment by brunocontrerasmoreira** [comment]
Thanks for spotting the typo.
Cron job is already set, the 4th every month, will check tomorrow if it finished successfully

**Comment by brunocontrerasmoreira** [comment]
Hi @cpommier , the updated JSON files are at ftp://ftp.ensemblgenomes.org/pub/misc_data/plant_index/ 
Let me know if you spot anything wrong, otherwise this can be closed,
Bruno

**Comment by cpommier** [comment]
It is ok, thanks
